# Generated by Django 4.2.23 on 2025-09-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'manager'), (2, 'employee')]),
        ),
    ]
